### PR TITLE
Moving Patterns to `/data/patterns/`

### PR DESCRIPTION
**Pull request by gsilvapt**
Pull request to fix issue #103 and #104.

The performed tasks were:
- [X] Move the list of patterns as per https://github.com/okfn/handbook/tree/ae934ab2efac136979a3765cf01ffae96fbc0e74/pattern from `/data-guides/` to `/data/patterns/`
-  [x] Rewrite the following files: `glossary.md`, `index.md`, `intro.md` - content copied from a previous version.
- [x] Move the contents from `/data-guides/` to `/data`, as per https://github.com/okfn/handbook/issues/104

Small updates refer to a few edits I did after talking with @rgrp about the quality of English and such.

---

PS: @rgrp Do not accept the PR if you don't think this solves the issue - let me know that instead. Thanks!

### CODE REVIEW

**Comment by rufuspollock** [comment]
@gsilvapt i am going to be strict on this as per our discussion and ask for a resubmit in smaller chunks 😉 Can i have (in order):
- the move of data patterns in one PR
- the rewrite in one PR
- moving the contents of data-guides to `/data/` in one PR

That way a given PR can fix a specific issue and these are easier to review.

You will probably need to close this pull request.

Lastly, please can you get more descriptive commit messages e.g. "PR to issue #xxx" does not tell me that much. You can say that but then add some info about what you actually did.

**Comment by gsilvapt** [comment]
@rgrp I thought this was already small. Yes, it has two commits, but those two are connected. I will work on a proper PR soon then.

**Comment by gsilvapt** [comment]
@rgrp I am a bit confused with the Git's usage for this issue. Should I do one change, submit pull requests and wait for your approval before submitting another PR? Or there is a way to submit separate pull requests?

**Comment by rufuspollock** [comment]
You have to submit one PR at a time I think. If you do that i will merge that one, then you submit another etc.

**Pull request closed without merging**
