### PR TITLE
added first basic conversions rst->md for /recipes etc

### PR DESCRIPTION
**Pull request by seralf**
I first converted data from:
https://github.com/okfn/datapatterns/tree/03892701946f3809e9eea3ad3a517f38e3600e04/text

then the /recipes from:
https://github.com/okfn/datapatterns/tree/master/text/recipes

there are several small styles to fix, and possible improvements.
Headers/metadata to add styles have not been yet added.

---

suggested **TODO**s:
- merge the two versions found for the glossary
- investigate how to handle properly footnotes in markdown (or extended markdown, extensions, and so on)
- check some missing images
- investigate how to create anchors to keywords in the glossary. As an idea: the glossary can also be used to create  an index to automatically enhance the pages with the proper reference.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@seralf where are the "courses" stuff coming from - i can't see the courses stuff in either the branches you are linking from (but I may be missing it). Are you sure you aren't copying over the courses stuff from your previous conversion?

**Comment by rufuspollock** [comment]
@seralf fixed typo in previous comment: "sources" should have been "courses". Where is the "courses" stuff in your commit coming from?

**Comment by seralf** [comment]
ah ok sorry for the typos, I was trying to apply those changes as soon as I
can (or I could work again on this in the next week, probably)

for the "/courses" material: it was from the earlier conversions from "
https://github.com/okfn/datapatterns/tree/master/text", If I'm not wrong it
could be deleted, but I left it in case it could be useful in some way. The
others are from the link cited in the previous conversations

2015-05-29 17:05 GMT+02:00 Rufus Pollock notifications@github.com:

**Comment by rufuspollock** [comment]
@seralf can you resubmit pull requst without the courses stuff. And then we get stuff in :-)

**Comment by seralf** [comment]
ok, removed here

**Comment by rufuspollock** [comment]
@seralf can you resubmit a pull request without the courses stuff - that way we have a clean commit (we don't add things then remove) - of you can "squash" these commits.

**Pull request closed without merging**
