### PR TITLE
Editing markdown

### PR DESCRIPTION
**Pull request by seralf**
HI I attempted [here](https://github.com/seralf/datapatterns/tree/editing-markdown) to run a first raw conversion / rewrite for the contents from `/courses` and `/text`: I hope I don't add typos / errors while editing :-)

Before doing the same for `/recipes`, and then trying to put the basic layout metadata, it's best to take a look at some of the issues I found with this process. Note that I tried to avoid changing text and structure where is possible.

Basically I run this procedure:
1. naively convert all the files from `.rst` to `.md` by pandoc
2. editing manually each file in order to correct some weird issue in formatting.
# ISSUES
- I had to rewrite all the notes / tasks (which at the moment use a `well` styling) in a format like:

```
=={.well}
text of the NOTE or TASK...
==
```

I used this as a placeholder to be able to later convert those to other formats, or processing them in some way.
- all the acronyms and commands cited should be probably rewritten adopting a convention: for example they could be rewritten as code using the ` ` ` character, or we could add to them a custom styling.
- the extra credits are sometimes at the beginning, and sometimes at the end of the files: I think they should be normalized.
- I did not change the references to external QUIZ with iframe, but the formatting should use the same template in each page
- there are several broken url references (to images) to fix

Please let me know if this could be a good starting point, or if I'm going completely in the wrong direction :-)

### CODE REVIEW

**Comment by rufuspollock** [comment]
@seralf this is great! One small item is that we actually don't want the courses stuff ;-0 - as per #69 the suggestion was

> Want content from point where we were still patterns (?)
> - This seems a likely point: https://github.com/okfn/datapatterns/tree/03892701946f3809e9eea3ad3a517f38e3600e04
> - Alternately we can go off master HEAD and just use the recipes - https://github.com/okfn/datapatterns/tree/master/text/recipes

Did you go back in the repo history to https://github.com/okfn/datapatterns/tree/03892701946f3809e9eea3ad3a517f38e3600e04?

`git checkout 03892701946f3809e9eea3ad3a517f38e3600e04`

I'd recommend doing that, doing the conversion and then commit that material in the gh-pages branch.

**Comment by seralf** [comment]
I'm sorry, I had the feeling I did not understand well :-)

I've started from V2 (
https://github.com/okfn/datapatterns/tree/03892701946f3809e9eea3ad3a517f38e3600e04):
the formatting requires some choice and change there and there, and my main
concern is avoiding loosing something. If this could pass as a good "raw"
draft, I suggest doing the same for `/recipes` (avoinding then instead the
`/courses` :-)) and eventually start rewriting with metadata, layouts...
this mainly because in this way probably other small issues in the
conversion emerges, and we can collect them to make choice.

What will be the template system? Jekyll? is it possible to use extensions?
I feel that for glossary or footnotes we probably have to use some
processor with extensions, as they are not supported but standard markdown,
neithr from multimarkdown or similar, as far as I can remember.

I wait for the gh-pages branch to be sure of what I'm doing, when we will
have something which you'll find on the right direction, I will switch to
that branch

2015-05-15 9:12 GMT+02:00 Rufus Pollock notifications@github.com:

**Comment by rufuspollock** [comment]
@seralf great! Let's not have courses - we don't plan to have those. I would use /patterns/ rather than recipes as per #70. Please commit into gh-pages branch and we can review the pull request.

Re template we are using jekyll - see #71. For theme see #72 - we need to work on this.

Shall we close this PR so you can open a new one?

**Comment by seralf** [comment]
yes, I'll work again on this in the next days and let you know... if I'll
have new questions I'll post them here
Closing this pull request should be fine, since we need some changes, thanks

2015-05-15 13:20 GMT+02:00 Rufus Pollock notifications@github.com:

**Comment by seralf** [comment]
sorry I didn't have yet time to push new updates, sorry: if everything goes ok I should be able to add something new before the weekend! :-)

**Comment by rufuspollock** [comment]
@seralf no problemo - and looking forward to the material once it lands.

**Comment by rufuspollock** [comment]
I will close this now.

**Comment by rufuspollock** [comment]
@seralf how's it going here? Any progress?

**Comment by seralf** [comment]
Hi Rufus, I finally have a (very-very raw and) first draft for the
conversion to markdown: several parts requires improvements, and there can
be typos of course, but starting from here we can add the header
information needed for integrating the template system, and then have
several single editings for improve the text in various way.
I suggest to create some guidelines for writing things, for example always
use upper case for acronyms, and so on. We have to investigate how to add
footnotes if needed, and how to convert TIPS and NOTES styles (sometimes
there and there I left them with a placeholder for the original style, in
order to recognize what need this changes).
Moreover I think it could be good to improve the glossary constructing
search over it to enhance the text by scripting, what do you think about?

2015-05-25 17:30 GMT+02:00 Rufus Pollock notifications@github.com:

**Comment by rufuspollock** [comment]
@seralf that's brilliant - do you want to open a new pull request ...

**Comment by seralf** [comment]
ok sorry I didn't... I've merged my editing-markdown on the gh-pages as
suggested earlier, and then created the pull

2015-05-29 15:25 GMT+02:00 Rufus Pollock notifications@github.com:

**Comment by todrobbins** [comment]
@seralf :+1:

**Comment by seralf** [comment]
eheh thank you Tod, sorry for creating some confusion!

2015-05-29 17:22 GMT+02:00 Tod Robbins notifications@github.com:

**Pull request closed without merging**
